name: BlockyRewards
version: '${version}'
main: dev.jayoxdev.blockyrewards.BlockyRewards
api-version: '1.20'
authors: [ JayoxDev ]
description: Give daily rewards to your users just for joining the server! Also give codes to redeem specials rewards
commands:
  blockyrewards:
    description: 'Command'
    aliases:
      - 'br'
  redeem:
    aliases:
      - 'redeemreward'
      - 'brredeem'
